Repository UCL/dxss, pull requests merged in 2024-04, with the labels that each got.

#55 Add a line about Maths dept to readme.
  README.md
Labels: documentation

#58 No longer need our own Givens rotation function.
  src/dxss/_utils.py
  tests/test_linear_algebra.py
Labels: housekeeping, refactoring

#56 Update linting to ruff "ALL" plus isort rules.
  .pre-commit-config.yaml
  pyproject.toml
  src/dxss/meshes.py
  src/dxss/solve_1d.py
  src/dxss/solve_2d.py
  src/dxss/solve_3d.py
  src/dxss/space_time.py
Labels: housekeeping

#63 Add support for dolfinx v0.7
  .github/workflows/tests.yml
  pyproject.toml
  src/dxss/meshes.py
Labels: housekeeping, core, testing

#57 Deduplication in meshes code
  src/dxss/meshes.py
Labels: housekeeping, refactoring

#59 Add backend type to matrix.
  .github/workflows/tests.yml
  pyproject.toml
Labels: housekeeping, testing
